language:
    - cpp

install:
    - sudo pip install cpp-coveralls

script:
    - cd tests
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./unit_tests

after_success:
    - coveralls --root ../.. -E ".*external.*" -E ".*CMakeFiles.*" -E ".tests/.*.cc.*"

notifications:
    email: false
